SELECT 

    `data`.`id` AS `id`,
    cast(`data`.`fecha_hora` as date) AS `fecha`,
    cast(`data`.`fecha_hora` as time) AS `hora`,
    `stations`.`label` AS `station`,
    `data`.`intervalo` AS `intervalo`,
    `data`.`temperatura_interna` AS `temperatura_interna`,
    `data`.`temperatura_externa` AS `temperatura_externa`,
    `data`.`humedad_interna` AS `humedad_interna`,
    `data`.`humedad_externa` AS `humedad_externa`,
    `data`.`presion_relativa` AS `presion_relativa`,
    `data`.`presion_absoluta` AS `presion_absoluta`,
    `data`.`velocidad_viento` AS `velocidad_viento`,
    `data`.`sensacion_termica` AS `sensacion_termica`,
    `data`.`rafaga` AS `rafaga`,
    `data`.`direccion_del_viento` AS `direccion_del_viento`,
    `data`.`punto_rocio` AS `punto_rocio`,
    `data`.`lluvia_hora` AS `lluvia_hora`,
    `data`.`lluvia_24_horas` AS `lluvia_24_horas`,
    `data`.`lluvia_semana` AS `lluvia_semana`,
    `data`.`lluvia_mes` AS `lluvia_mes`,
    `data`.`lluvia_total` AS `lluvia_total`,
    `data`.`hi_temp` AS `hi_temp`,
    `data`.`low_temp` AS `low_temp`,
    `data`.`wind_cod` AS `wind_cod`,
    `data`.`wind_run` AS `wind_run`,
    `data`.`hi_speed` AS `hi_speed`,
    `data`.`hi_dir` AS `hi_dir`,
    `data`.`wind_cod_dom` AS `wind_cod_dom`,
    `data`.`wind_chill` AS `wind_chill`,
    `data`.`index_heat` AS `index_heat`,
    `data`.`index_thw` AS `index_thw`,
    `data`.`index_thsw` AS `index_thsw`,
    `data`.`rain` AS `rain`,
    `data`.`solar_rad` AS `solar_rad`,
    `data`.`solar_energy` AS `solar_energy`,
    `data`.`radsolar_max` AS `radsolar_max`,
    `data`.`uv_index` AS `uv_index`,
    `data`.`uv_dose` AS `uv_dose`,
    `data`.`uv_max` AS `uv_max`,
    `data`.`heat_days_d` AS `heat_days_d`,
    `data`.`cool_days_d` AS `cool_days_d`,
    `data`.`in_dew` AS `in_dew`,
    `data`.`in_heat` AS `in_heat`,
    `data`.`in_emc` AS `in_emc`,
    `data`.`in_air_density` AS `in_air_density`,
    `data`.`evapotran` AS `evapotran`,
    `data`.`soil_1_moist` AS `soil_1_moist`,
    `data`.`soil_2_moist` AS `soil_2_moist`,
    `data`.`leaf_wet1` AS `leaf_wet1`,
    `data`.`leaf_wet2` AS `leaf_wet2`,
    `data`.`leaf_wet3` AS `leaf_wet3`,
    `data`.`leaf_wet4` AS `leaf_wet4`,
    `data`.`wind_samp` AS `wind_samp`,
    `data`.`wind_tx` AS `wind_tx`,
    `data`.`iss_recept` AS `iss_recept`,
    `data`.`meteobridge` AS `meteobridge`

FROM (`data` LEFT JOIN `stations` ON((`stations`.`id` = `data`.`id_station`)))